import {
  MAX_COMMAND_ENTRY_BYTES,
  MAX_IDENTIFIER_BYTES,
  MAX_REGULAR_TEXT_BYTES,
} from "../validation";

export const MAX_PLANNING_DECISION_BYTES = 32 * 1024;
export const MAX_PLANNING_SCOPE_ITEMS = 16;
export const MAX_PLANNING_ACCEPTANCE_CRITERIA = 16;
export const MAX_PLANNING_CONSTRAINTS = 16;
export const MAX_PLANNING_RISKS = 16;
export const MAX_PLANNING_VERIFICATIONS = 16;
export const MAX_PLANNING_WORK_UNITS = 32;
export const MAX_WORK_UNIT_REFERENCES = 16;
export const MAX_PLANNING_FINAL_VERIFICATIONS = 16;
export const MAX_UNRESOLVED_DECISIONS = 8;
export const MAX_PLANNING_TEXT_BYTES = MAX_REGULAR_TEXT_BYTES;
export const MAX_PLANNING_IDENTIFIER_BYTES = MAX_IDENTIFIER_BYTES;
export const MAX_PLANNING_COMMAND_BYTES = MAX_COMMAND_ENTRY_BYTES;
export const MAX_VERIFICATION_TIMEOUT_MS = 86_400_000;
